language: node_js

node_js:
  - 10
  - 12

stages:
  - build
  - prettier
  - test

jobs:
  include:
    - stage: prettier
      name: "Prettier Formatting Check"
      script: npm run lint
    - stage: build
      name: "Build"
      script: npm run clean && npm run build
    - stage: test
      script: npm run test-coverage
