language: node_js

install:
  - npm install -g codecov
  - npm install

node_js:
  - 8
  - 10
  - 12

stages:
  - validate
  - test

jobs:
  include:
    - stage: validate
      name: "Prettier Format Check"
      script: npm run lint

script:
  - npm run test-coverage
  - codecov
