name: firestore_counter
description: A Dart client for using Firestore Distributed Counter.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  async: ^2.9.0
  cloud_firestore: ^4.3.1
  uuid: ^3.0.7

dev_dependencies:
