name: e2e

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "firestore-counter/clientst/**"
  push:
    branches:
      - "**"
    paths:
      - "firestore-counter/clients/**"
jobs:
  ios:
    runs-on: macos-12
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        name: Install Node.js 14
        with:
          node-version: "14"
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
      - uses: hendrikmuhs/ccache-action@v1
        name: Xcode Compile Cache
        with:
          key: ${{ runner.os }}-ios-v3
          max-size: 700M
      - uses: actions/cache@v2
        name: Pods Cache
        id: pods-cache
        with:
          path: tests/ios/Pods
          key:
            ${{ runner.os }}-pods-v3-${{ hashFiles('tests/ios/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-ios-pods-v2
      - name: Firebase Emulator
        run: |
          cd ./_emulator
          firebase emulators:start
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: "Install Tools"
        run: |
          sudo npm i -g firebase-tools
      - name: "E2E Tests"
        working-directory: tests
        run: |
          # Boot simulator and wait for System app to be ready.
          SIMULATOR="iPhone 11"
          xcrun simctl bootstatus "$SIMULATOR" -b
          xcrun simctl logverbose "$SIMULATOR" enable
          # Sleep to allow simulator to settle.
          sleep 15
          # Uncomment following line to have simulator logs printed out for debugging purposes.
          # xcrun simctl spawn booted log stream --predicate 'eventMessage contains "flutter"' &
          firebase emulators:exec 'cd ../firestore-counter/clients/dart && flutter test integration_test' -d "$SIMULATOR"
          FLUTTER_DRIVE_EXIT_CODE=$?
          xcrun simctl shutdown "$SIMULATOR"
          exit $FLUTTER_DRIVE_EXIT_CODE
