name: Testing

on:
  push:
    branches: [next]
  pull_request:
    branches: ["**"]

jobs:
  nodejs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node: ["20"]
    name: node.js_${{ matrix.node }}_test
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: npm install
        run: npm i
      - name: Build emulator functions
        run: cd _emulator/functions && npm i && npm run build & cd ../..
      - name: Install Firebase CLI
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: npm i -g firebase-tools@14
      - name: Setup e2e secrets
        run: |
          echo SMTP_PASSWORD=${{ secrets.SENDGRID_API_KEY }} >> _emulator/extensions/firestore-send-email-sendgrid.secret.local
      - name: npm test
        run: npm run test:ci
