name: Validate

on:
  pull_request:
    branches:
      - "**"

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: NPM install
        run: npm pkg set scripts.postinstall="echo no-postinstall" && npm i
      - name: Prettier Lint Check
        run: npm run lint
