name: Validate

on:
  pull_request:
    branches:
      - "**"

jobs:
  formatting:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7
        with:
          node-version: 20
      - name: NPM install
        run: SKIP_POSTINSTALL=yes npm i
      - name: Prettier Lint Check
        run: npm run lint
