name: Validate

on:
  pull_request:
    branches:
      - "**"

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: NPM install
        run: npm i
      - name: Prettier Lint Check
        run: npm run lint
